# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy local code to the container image.
COPY . /app

# Install pip dependencies
RUN pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple \
    && pip install . -i https://pypi.tuna.tsinghua.edu.cn/simple

# Expose necessary port if any (MCP typically uses stdio, but if needed, uncomment below)
# EXPOSE 8001

# Run the MCP Server mcp-proxy --sse-host=0.0.0.0 --sse-port=8080 uvx your-server
CMD ["python", "src/main.py"]
