[project]
name = "mongodb-mcp-server"
version = "0.1.0"
description = "MongoDB MCP Server, by MongoDB"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.5.0",
    "pymongo>=4.12.0",
    "dotenv>=0.9.9",
    "numpy>=2.2.4",
]
